# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Arabic Site Configuration
lang: ar
direction: rtl
dir: rtl

title: مدونتي العربية
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  مدونة عربية حديثة باستخدام Jekyll مع دعم كامل للغة العربية
  والكتابة من اليمين إلى اليسار. تصميم أنيق وبسيط للمحتوى العربي.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
repository: yourusername/arabic-blog
twitter: yourusername
github: yourusername

google_analytics:
comments: false
disqus:

author: محمد الحقباني
author_bio: >-
  مرحباً! أنا محمد، كاتب ومطور ويب متخصص في إنشاء المحتوى العربي الرقمي.
  أشارك هنا أفكاري وتجاربي في البرمجة والتقنية والثقافة العربية.
author_pic: https://via.placeholder.com/150

paginate: 4
paginate_path: "/:num/"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
permalink: /:title

# Optional: If you switch to jekyll-paginate-v2, replace the above with:
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag
#   - jekyll-paginate-v2
#   - jekyll-sitemap
#
# pagination:
#   enabled: true
#   per_page: 5
#   permalink: "/page/:num/"
#   title: ":title - page :num"

theme_switcher: false

# Allows all pages to be put into `_pages` folder
# for easier navigation and better SEO.
collections:
  pages:
    output: true
    permalink: /:title

# Exclude from processing.
exclude:
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
  - "theme"
  - "sandbox"

# Optional: Sass configuration (requires enabling Sass gems; see Gemfile comments)
# sass:
#   style: compressed
#   load_paths:
#     - assets/scss
